-- Homework 4: https://www.w3resource.com/sql-exercises/sql-fromatting-output-exercises.php

/* 1. From the following table, write a SQL query to select all the salespeople. 
Return salesman_id, name, city, commission with the percent sign (%). 
Sample table: salesman */

select salesman_id, name, city, '%' as 'percent', commission*100 as commission from salesman

select salesman_id, name, city, concat(commission, '%') as commission from salesman

/*2. From the following table, write a SQL query to find the number of orders booked for each day. 
Return the result in a format like "For 2001-10-10 there are 15 orders".". 
Sample table: orders */

select 
  ' For', 
  ord_date, 
  ', there are ',  -- shu joyda vergul qo'ymagan ekanman boshda, ancha vaqt nima erro ekan deb count ni o'zgartrb yotman (
  COUNT(ord_no), 
  'orders.' 
from 
  orders 
group by 
  ord_date


/*3. From the following table, write a SQL query to find all the orders. 
Sort the result-set in ascending order by ord_no. Return all fields.  
Sample table: orders */

select * from orders
order by ord_no asc

/*4. From the following table, write a SQL query to find all the orders. 
Sort the result-set in descending order by ord_date. Return all fields. 
Sample table: orders */

select * from orders
order by ord_no desc

/*5. From the following table, write a SQL query to find all the orders. 
Sort the result-set in descending order by ord_date and purch_amt. Return all fields.  
Sample table: orders*/

select * from orders
order by ord_date desc, purch_amt desc

/*6. From the following table, write a SQL query to find all the customers. 
Sort the result-set by customer_id. Return cust_name, city, grade. 
Sample table: customer */

select cust_name, city, grade from customer
order by customer_id

/* 7. From the following table, write a SQL query that calculates the maximum purchase amount generated by each 
salesperson for each order date. Sort the result-set by salesperson id and order date in ascending order. 
Return salesperson id, order date and maximum purchase amount. 
Sample table: orders */

select salesman_id, ord_date, MAX(purch_amt) from orders
group by salesman_id, ord_date
order by salesman_id, ord_date

/*8. From the following table, write a SQL query to find all the customers. 
Sort the result-set in descending order on 3rd field. Return customer name, city and grade.  
Sample table: customer*/

select cust_name, city, grade from customer
order by 3 desc

/*9. From the following table, write a SQL query that counts the unique orders and the highest purchase amount 
for each customer. Sort the result-set in descending order on 2nd field. 
Return customer ID, number of distinct orders and highest purchase amount by each customer. 
Sample table: orders*/ 

select customer_id, count(distinct ord_no) 'count', max(purch_amt) 'max' from orders
group by customer_id
order by count(distinct ord_no) desc

/*10. From the following table, write a SQL query to calculate the summation of purchase amount, 
total commission (15% for all salespeople) by each order date. 
Sort the result-set on order date. Return order date, summation of purchase amount and commission.
Sample table : orders*/

select ord_date, sum(purch_amt) 'sum_purch', sum(purch_amt)*0.15 'commission' from orders
group by ord_date

-- complete