-- 📌Homework📌
-- task 1 (joins) — https://www.w3resource.com/sql-exercises/sql-joins-exercises.php
-- task 2 (joins-hr) — https://www.w3resource.com/sql-exercises/joins-hr/index.php
-- task 3 (joins-movie) — https://www.w3resource.com/sql-exercises/movie-database-exercise/joins-exercises-on-movie-database.php
